---

- name: install packages
  package: name={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2
  become: yes

- name: update hba config
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640
  notify: restart postgres
  become: yes

- name: setup service
  service: name=postgresql state=started enabled=yes
  become: yes

- name: create DBs
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: '{{ item }}'
  loop: '{{ postgres_dbs }}'
  become_user: postgres
  become: yes
  when: postgres_dbs is defined

- name: create users
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    name: '{{ item.user }}'
    password: '{{ item.pass }}'
    db: '{{ item.db }}'
  loop: '{{ postgres_users }}'
  become_user: postgres
  become: yes
  when: postgres_users is defined
