---

- name: create DB
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: gogs
  become_user: postgres
  become: yes

- name: create DB user
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    name: gogs
    db: gogs
    password: '{{ gogs_db_pass }}'
  become_user: postgres
  become: yes

- name: ensure Gogs data dir structure
  file: path={{ gogs_root }}/gogs/conf state=directory recurse=yes owner={{ ansible_user_id }}
  become: yes

- name: setup Gogs configuration
  template: src=templates/app.ini.j2 dest={{ gogs_root }}/gogs/conf/app.ini mode='640'
  notify: restart gogs

- name: run Gogs docker container
  docker_container:
    name: gogs
    image: gogs/gogs
    restart_policy: unless-stopped
    ports:
      - "{{ gogs_ssh_port }}:22"
    volumes:
      - "{{ gogs_root }}:/data"
      - /var/run/postgresql:/var/run/postgresql
    networks:
      - name: frontend
  become: yes

- name: modify UFW to SSH
  ufw: rule=allow port={{ gogs_ssh_port }} proto=tcp
  become: yes
