- name: pip
  apt: name={{ item }} state=latest
  become: yes
  with_items:
    - python-pip

- name: dev packages
  pip: name={{ item }} state=latest
  become: yes
  with_items:
    - pip
    - virtualenv
    - virtualenvwrapper
    - flake8
