---

- name: packages
  package: name={{ item }} state=latest
  with_items:
    - transmission-cli
    - transmission-daemon
    - transmission-common

- name: group membership
  user: name=debian-transmission groups={{ media_group }} append=yes
  become: yes

- name: configuration
  lineinfile:
    path: /etc/transmission-daemon/settings.json
    regexp: "^    \"{{ item.name }}\""
    line: "    \"{{ item.name }}\": {{ item.value }}, "
  with_items:
    - { name: 'rpc-whitelist', value: "\"{{ transmission_whitelist }}\"" }
    - { name: 'port-forwarding-enabled', value: "{{ transmission_port_fwd }}" }
    - { name: 'peer-port-random-on-start', value: "{{ transmission_random_port }}" }
    - { name: 'ratio-limit', value: "{{ '%.4f'|format(transmission_ratio_limit|float) }}" }
    - { name: 'ratio-limit-enabled', value: "{{ transmission_ratio_limit_enabled }}" }
    - { name: 'idle-seeding-limit', value: "{{ transmission_idle_seeding_limit }}" }
    - { name: 'idle-seeding-limit-enabled', value: "{{ transmission_idle_seeding_limit_enabled }}" }
    - { name: 'download-dir', value: "\"{{ transmission_download_dir }}\"" }
    - { name: 'incomplete-dir', value: "\"{{ transmission_incomplete_dir }}\"" }
  notify: reload transmission config

- name: systemd config dir
  file: path=/etc/systemd/transmission.service state=directory recurse=yes
  become: yes

- name: systemd config file
  copy:
    content: |
      [Unit]
      Requires=network.target
    dest: /etc/systemd/transmission.service/fixdep.conf
  become: yes
  notify: reload transmission config
