---

- name: packages
  package: name={{ item }} state=latest
  with_items:
    - transmission-cli
    - transmission-daemon
    - transmission-common

- name: group membership
  user: name=debian-transmission groups={{ media_group }} append=yes
  become: yes

- name: configuration
  lineinfile:
    path: /etc/transmission-daemon/settings.json
    regexp: "^    \"{{ item.name }}\""
    line: "    \"{{ item.name }}\": {{ item.value }}, "
  with_items:
    - { name: 'rpc-whitelist', value: "\"{{ transmission_whitelist }}\"" }
    - { name: 'port-forwarding-enabled', value: "{{ transmission_port_fwd }}" }
    - { name: 'peer-port-random-on-start', value: "{{ transmission_random_port }}" }
    - { name: 'umask', value: "{{ transmission_umask }}" }
    - { name: 'ratio-limit', value: "{{ '%.4f'|format(transmission_ratio_limit|float) }}" }
    - { name: 'ratio-limit-enabled', value: "{{ transmission_ratio_limit_enabled }}" }
    - { name: 'idle-seeding-limit', value: "{{ transmission_idle_seeding_limit }}" }
    - { name: 'idle-seeding-limit-enabled', value: "{{ transmission_idle_seeding_limit_enabled }}" }
    - { name: 'download-dir', value: "\"{{ transmission_download_dir }}\"" }
    - { name: 'download-queue-size', value: "{{ transmission_download_queue_size }}" }
    - { name: 'incomplete-dir', value: "\"{{ transmission_incomplete_dir }}\"" }
    - { name: 'incomplete-dir-enabled', value: "{{ transmission_incomplete_dir_enabled }}" }
    - { name: 'download-limit', value: "{{ transmission_download_limit }}" }
    - { name: 'download-limit-enabled', value: "{{ transmission_download_limit_enabled }}" }
    - { name: 'upload-limit', value: "{{ transmission_upload_limit }}" }
    - { name: 'upload-limit-enabled', value: "{{ transmission_upload_limit_enabled }}" }
  become: yes
  notify: reload transmission config

- name: sysctl settings
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_file: /etc/sysctl.d/transmission.conf
  with_items:
    - { name: 'net.core.wmem_max', value: 1048576 }
    - { name: 'net.core.rmem_max', value: 4194304 }
  become: yes
  notify: reload transmission config

- name: systemd config
  copy:
    src: files/transmission-daemon.service
    dest: /lib/systemd/system/transmission-daemon.service
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: reload systemd

- name: systemd network-wait depdencies
  systemd: name={{ item }} enabled=yes
  with_items:
    - systemd-networkd.service
    - systemd-networkd-wait-online.service
