- name: Debian-based distro setup
  block:

  - name: update apt cache
    apt: update_cache=yes
    become: yes
    changed_when: no
  
  - name: install git
    apt: name={{ item }} state=latest
    become: yes
    with_items:
      - git

  when: ansible_os_family == 'Debian'

- name: RHEL-based distro setup
  block:

  - name: install git
    yum: name={{ item }} state=latest
    become: yes
    with_items:
      - git

  when: ansible_os_family == 'RedHat'
