---

- name: distribution setup
  include_tasks: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution|lower }}.yml"
    - "setup-{{ ansible_os_family|lower }}.yml"
    - setup-default.yml

- name: install git
  package: name={{ item }} state=latest
  become: yes
  with_items:
    - git
