---

# Only needed for Arch
- name: install arch packages
  package: name={{ package }} state=latest
  with_items:
    - inetutils
    - coreutils
    - fzf
  loop_control:
    loop_var: package
  become: yes
