---
- name: create user
  user: name=jenkins
  become: yes

- name: ensure dir structure
  file: path={{ jenkins_root }}/secrets state=directory recurse=yes owner=1000 group=1000
  become: yes

- name: run container
  docker_container:
    name: jenkins-master
    image: jenkins/jenkins:lts-alpine
    restart_policy: unless-stopped
    volumes:
      - "{{ jenkins_root }}:/var/jenkins_home"
    networks:
      - name: frontend
  become: yes
