---

- name: install pip
  package: name=python-pip state=latest
  become: yes

- name: install docker-py
  pip: name=docker-py state=latest
  become: yes

- name: enable service
  systemd: name=docker state=started enabled=yes
  become: yes

- name: create frontend network
  docker_network: name=frontend
  become: yes
