---
- name: remove docker-py
  pip:
    name: docker-py
    state: absent
  become: yes

- name: Install docker python module
  pip:
    name: "docker-compose==1.12.0"
  become: yes

- name: enable service
  systemd: name=docker state=started enabled=yes
  become: yes

- name: create frontend network
  docker_network: name=frontend
  become: yes
