---

- name: distribution setup
  include_tasks: "{{ item }}"
  with_first_found:
    - "setup-{{ ansible_distribution|lower }}.yml"
    - "setup-{{ ansible_os_family|lower }}.yml"
    - setup-default.yml

- name: my vim config
  git: repo=ssh://git@github.com/belminf/dotvim.git dest=~/.vim accept_hostkey=yes update=yes recursive=yes
  notify: install vim plugins

- name: link new vim
  file: src=~/.vim/rc.vim dest=~/.vimrc state=link
