- name: Debian-based distro setup
  block:

  - name: update apt cache
    apt: update_cache=yes
    become: yes
    changed_when: no
  
  - name: install vim requirements
    apt: name={{ item }} state=latest
    become: yes
    with_items:
      - vim-nox
      - silversearcher-ag

  when: ansible_os_family == 'Debian'

- name: RHEL-based distro setup
  block:

  - name: install vim requirements
    yum: name={{ item }} state=latest
    become: yes
    with_items:
      - vim

  when: ansible_os_family == 'RedHat'

- name: my vim config
  git: repo=ssh://git@github.com/belminf/dotvim.git dest=~/.vim accept_hostkey=yes update=yes recursive=yes force=yes
  register: vim_git

- name: link new vim
  file: src=~/.vim/rc.vim dest=~/.vimrc state=link

- name: install vim plugins
  command: vim +PlugInstall +qall
  when: vim_git.changed
