---
- name: update apt cache
  apt: update_cache=yes
  become: yes
  changed_when: no

- name: install vim requirements
  apt: name={{ package }} state=latest
  loop_control:
    loop_var: package
  become: yes
  with_items:
    - vim-nox
    - silversearcher-ag
    - pick
