---

- hosts: servers
  roles:
    -
      role: package_upgrade
      tags: upgrade
  tasks:
    - name: reboot server
      shell: sleep 2 && shutdown -r now "Ansible reboot"
      async: 1
      poll: 0
      become: yes
      tags: reboot

    - name: wait for server
      local_action: wait_for host={{ ansible_default_ipv4['address'] }} port=22 state=started delay=10
      become: false
      tags: reboot
