---
- hosts: all
  remote_user: pi
  become: yes
  vars_files:
    - vault.yml
  roles:
    - plex_media_server
    -
      role: transmission
      transmission_ratio_limit: '{{ vault_pi_transmission_ratio_limit }}'
