- import_playbook: linux.yml
  tags: linux

- hosts: all
  vars_files:
    - vault.yml
  vars:
    caddy_root: /srv/caddy
    site_name: belm.info
  roles:
    - golang
    - python
    - tmux
    - 
      role: website
      caddy_root: /srv/caddy
      site_name: belm.in
      redirects: www.belm.in, belm.info, workbench.belm.info
      proxies:
        - from: git.belm.in
          to: gogs:3000
      tags: update_website
    -
      role: postgresql
      tags: db
    -
      role: gogs
      gogs_root: /srv/gogs
      gogs_db_type: postgres
      gogs_disable_registration: true
      gogs_db_host: '{{ vault_gogs_db_host }}'
      gogs_db_name: '{{ vault_gogs_db_name }}'
      gogs_db_user: '{{ vault_gogs_db_user }}'
      gogs_db_pass: '{{ vault_gogs_db_pass }}'
      gogs_db_ssl: '{{ vault_gogs_db_ssl }}'
      gogs_db_path: '{{ vault_gogs_db_path }}'
      gogs_domain: '{{ vault_gogs_domain }}'
      gogs_http_port: '{{ vault_gogs_http_port }}'
      gogs_root_url: '{{ vault_gogs_root_url }}'
      gogs_ssh_port: '{{ vault_gogs_ssh_port }}'
      gogs_secret_key: '{{ vault_gogs_secret_key }}'
      gogs_mailer_host: '{{ vault_gogs_mailer_host }}'
      gogs_mailer_from: '{{ vault_gogs_mailer_from }}'
      tags: gogs
